# -*- coding: utf-8 -*-
"""day2__lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mzxQdZRHvrbrmFMbD6H2DU4QQsHYdvAg

# Lab3

1. Write a program that takes a number from the user and determines whether it's even or odd.

	output: odd or even
"""

num = input()
if(int(num)%2==1):
    print('odd')
else:
    print('even')

"""2. Write a program that takes three numbers from the user and determines the largest of the three.



"""

fnum= eval(input('fnum :'))
snum= eval(input('snum :'))
tnum= eval(input('tnum :'))

largest = fnum
if snum>largest:
     largest=snum
if tnum>largest:
     largest=tnum
print(str(largest))

"""
3. Write a program that reads an integer as input and determines if it is a multiple of both 3 and 5.

	output: multiple or not multiple

"""

num=input('정수입력 :')
if(int(num)%5==0 & int(num)%3==0):
  print('multiple')
else:
  print('not multiple')

"""
4. Write a Python program that takes three numbers as input and determines whether they form a Pythagorean triple.

	output: pythagorean or not pythagorean"""

a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
c = int(input("Enter the third number: "))

if a**2 + b**2 == c**2 or a**2 + c**2 == b**2 or b**2 + c**2 == a**2:
    print("pythagorean")
else:
    print("not pythagorean")

"""5. Write a Python program that takes a user's weight and height as input and calculates their body mass index (BMI). 

	output: < 18.5 : underweight, 18.5 - 24.9 normal weight, <= 25.0 overweight





"""

height = float(input("Enter your height in meters: "))
weight = float(input("Enter your weight in kilograms: "))

bmi = weight / (height ** 2)

if bmi < 18.5:
    print(bmi, "underweight.")
elif bmi >= 18.5 and bmi <= 24.9:
    print(bmi, "normal weight.")
else:
    print(bmi, "overweight.")

"""6. Write a Python program that takes two strings as input and determines whether they are anagrams. If the two strings are anagrams (i.e., they have the same letters in a different order)

  output: anagrams or not anagrams
"""



"""# Lab4

1. Write a program to find the sum of all numbers between 1 and 100 that are divisible by 7 using a while loop.
"""

total = 0  
i = 1 

while i <= 100: 
    if i % 7 == 0: 
        total += i 
    i += 1 

print(total)

"""2. Write a program that prints the multiplication table for a given number using a for loop."""

num = int(input("Enter a number: "))

print("Multiplication table for", num)

for i in range(1, 11):
    print(num, "x", i, "=", num*i)

"""3. Write a program that reads a positive integer and checks if it's a prime number using a for loop."""

# 소수 1과 자기자신만을 약수로 가짐 
num=input()

"""4. Write a program that reads a string and reverses it using a loop. The program should also count and display the number of vowels in the string.

"""



"""5. Write a program that prints the following patterns using loops:

```
*****
 ****
  ***
   **
    *
```
"""



"""6. Create a shopping list program that allows the user to add item names to the list, remove items, and display the list using loops. The program should continuously ask the user for input until they choose to exit.


```
Choose an option:
1. Add item name
2. Remove item by name
3. Display list
4. Exit
```

"""

